### ISSUE TITLE
CompanySearch returns a too long a list

### ISSUE THREAD

**Issue by lawrencebywater** [MatthewSmith430/CompaniesHouse#1]
Ideally need an argument whereby only the first result is returned, I am finding for almost all company names the list returned is so long that the function eventually falls over and returns the following error:
" Error: parse error: premature EOF
                                       
                     (right here) ------^ "

**Comment by MatthewSmith430** [comment]
I have added two new functions:

`CompanySearch_limit`
This return the first page of results – so the first 20 results

`CompanySearch_limit_first`
This return the first search result only

Therefore – these can be used when you have a specific search term, but for more general search terms – like “bitcoin” the `CompanySearch` function can be used.

Kind regards,

Matthew

**Comment by lawrencebywater** [comment]
Thanks, that’s awesome. On a sort of related note, i am having issues when searching for companies that have an ‘&’ in the name.

E.g. ‘D & G investments limited’ will return a company just called ‘D’.

Many thanks
Lawrence

lawrencebywater@gmail.com<mailto:lawrencebywater@gmail.com> | (+44) 07743780996

On 15 Dec 2018, at 16:48, Matthew Smith <notifications@github.com<mailto:notifications@github.com>> wrote:


I have added two new functions:

CompanySearch_limit
This return the first page of results – so the first 20 results

CompanySearch_limit_first
This return the first search result only

Therefore – these can be used when you have a specific search term, but for more general search terms – like “bitcoin” the CompanySearch function can be used.

Kind regards,

Matthew

**Comment by MatthewSmith430** [comment]
Thanks for pointing that out. I have corrected that - it should now work.

Kind regards,

Matthew
