### ISSUE TITLE
Pure GET package for API

### ISSUE THREAD

**Issue by stephlocke** [MatthewSmith430/CompaniesHouse#2]
Hi Matthew,
I'm looking to build/use a package that has robust coverage of the companies house API. I see you have a core function that returns data from one of the endpoints. If I built a package that covers the endpoints and provides a raw list variant for the GET companies option - would you be interested in depending on it? 

The reason I ask that way versus asking about extending your package is that your package seems to have a specific network analysis focus for the data.

Cheers,
Steph

**Comment by MatthewSmith430** [comment]
Hi @stephlocke 

Apologies I have replied to this so late. I would be be interested in hearing more and depending on it. Yes - this package is mainly focused on networks, where I chiefly use it for crating networks of interlocking directorates. 

Kind regards,
Matthew (M.Smith@greenwich.ac.uk)
