### ISSUE TITLE
Error installing package

### ISSUE THREAD

**Issue by AhmedB100** [MatthewSmith430/CompaniesHouse#3]
Hi Matthew,

I am attempting to install the package on my mac (MacOS High Sierra) and get the following error: 

ERROR: dependency ‘installr’ is not available for package ‘CompaniesHouse’

I believe installr only works on Windows. Do you have an easy fix for this?

Thanks!

**Comment by MatthewSmith430** [comment]
Hi @AhmedB100 

Thanks for highlighting this - I have now removed the dependency on installr. 

Kind regards,

Matthew
